NOME = input("Qual o seu nome? ")
NASCIMENTO = input("Qual o seu ano de nascimento? ")
IDADE = 2024 - int( NASCIMENTO)
CIDADE = input("Qual a sua cidade? ")
print("Olá", NOME, "você tem", IDADE, "anos.","VOCE NASCEU EM ",CIDADE,)
print("Olá {} você tem {} anos. VOCE NASCEU EM {}".format(NOME, IDADE, CIDADE))